[[redirects]]
  # SPA redirect
  from = "/*"
  to = "/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "deny"
    Content-Security-Policy = "frame-ancestors 'self';"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000"
